### PR TITLE
Amelia Waggoner

### PR DESCRIPTION
**Pull request by GoldenDog190**
Added more to the about us page. Installed SASS, and then set up the SCSS files for SASS CSS, but couldn’t get the SASS CSS to work. So, I then set up the CSS files for the styling for now and worked in the main.css to start setting up the styling.

### CODE REVIEW

**Review by baxance — APPROVED** [review]
lgtm

**Review by baxance — APPROVED** [review]
lgtm

**Review by mparkersimms — APPROVED** [review]

**Review by mparkersimms — COMMENTED** [review]
,jhk;jn

**Review by mparkersimms — COMMENTED** [review]
klhgkl

**Pull request merged**
